\newlabel{NeutrinoDiscovery}
\newlabel{NeutrinoPrediction}
\newlabel{RepresentingEVDData}
\newlabel{SolarNeutrinoProblem}
\newlabel{chap:35tonAnalysis}
\newlabel{chap:35ton}
\newlabel{chap:DUNE}
\newlabel{chap:FDAnalysis}
\newlabel{chap:Introduction}
\newlabel{chap:LArTPCReconstruction}
\newlabel{chap:NeutrinoPhysics}
\newlabel{chap:OnlineMonitoring}
\newlabel{chap:Summary}
\newlabel{eq:BetaDecayEnergy}
\newlabel{eq:DataPi0CandidateMass}
\newlabel{eq:DavisAntineutrino}
\newlabel{eq:DavisNeutrino}
\newlabel{eq:ElectronLifetime}
\newlabel{eq:ElectronLifetime}
\newlabel{eq:ElectronNeutrinoAppearance}
\newlabel{eq:FlavourEvolution}
\newlabel{eq:FlavourMassStates}
\newlabel{eq:FlavourSuperposition}
\newlabel{eq:FlavourTimeEvolution}
\newlabel{eq:InverseBetaDecay}
\newlabel{eq:MassSuperposition}
\newlabel{eq:MassTimeEvolution}
\newlabel{eq:MuonNeutrinoDisappearance}
\newlabel{eq:NeutrinoAntineutrinoAsymmetry}
\newlabel{eq:PMNS}
\newlabel{eq:RelativisticEnergyMomentum}
\newlabel{eq:RelativisticEnergy}
\newlabel{eq:ScintillationExcitation}
\newlabel{eq:ScintillationIonisation}
\newlabel{fig:2DnumuCCClusters}
\newlabel{fig:2DnumuCCHits}
\newlabel{fig:2DnumuCC}
\newlabel{fig:35tonCameraDiagram}
\newlabel{fig:35tonCameraMounted}
\newlabel{fig:35tonCameraPhoto}
\newlabel{fig:35tonCameraSchematic}
\newlabel{fig:35tonCamerasDegredation}
\newlabel{fig:35tonCamerasImages}
\newlabel{fig:35tonCamera}
\newlabel{fig:35tonCryostat}
\newlabel{fig:35tonDataFormat}
\newlabel{fig:35tonDetector}
\newlabel{fig:35tonExternalCounters}
\newlabel{fig:35tonFilling}
\newlabel{fig:35tonGasFilling}
\newlabel{fig:35tonGeometry}
\newlabel{fig:35tonLAPD}
\newlabel{fig:35tonLiquidFilling}
\newlabel{fig:35tonPhaseIElectronLifetime}
\newlabel{fig:35tonPhaseIIData}
\newlabel{fig:35tonPhotonDetectorsAttenuation}
\newlabel{fig:35tonPhotonDetectorsResolution}
\newlabel{fig:35tonPhotonDetectors}
\newlabel{fig:35tonPhoto}
\newlabel{fig:35tonPipeBreak}
\newlabel{fig:35tonTriggeredEvent}
\newlabel{fig:35tonTriggering}
\newlabel{fig:3DnumuCC2D}
\newlabel{fig:3DnumuCC3D}
\newlabel{fig:3DnumuCC}
\newlabel{fig:APACrossingAligmentLeastSqResidual}
\newlabel{fig:APACrossingAligmentLeastSqSeparation}
\newlabel{fig:APACrossingAlignmentLeastSqMin}
\newlabel{fig:APACrossingAlignmentLeastSq}
\newlabel{fig:APACrossingAlignmentSeparationMin}
\newlabel{fig:APACrossingAlignmentSeparation}
\newlabel{fig:APAGapCrosser}
\newlabel{fig:APAGapCrossingGaps}
\newlabel{fig:APAGapMCXOffsetZOffsetAngle}
\newlabel{fig:APAGapMCXOffsetZOffsetAngle}
\newlabel{fig:APAGapMCXOffsetZOffset}
\newlabel{fig:APAGapMCXOffsetZOffset}
\newlabel{fig:APAGapMCZOffset}
\newlabel{fig:APAGapMCZOffset}
\newlabel{fig:APAGapMC}
\newlabel{fig:APAGapMC}
\newlabel{fig:APAGapXOffsetNegFix}
\newlabel{fig:APAGapXOffsetNeg}
\newlabel{fig:APAGapXOffsetPosFix}
\newlabel{fig:APAGapXOffsetPos}
\newlabel{fig:APAGapXOffsetZOffsetNegFix}
\newlabel{fig:APAGapXOffsetZOffsetNeg}
\newlabel{fig:APAGapXOffsetZOffsetPosFix}
\newlabel{fig:APAGapXOffsetZOffsetPos}
\newlabel{fig:APAGapXOffsetZOffset}
\newlabel{fig:APAGapXOffset}
\newlabel{fig:APAGapZOffsetCorrected}
\newlabel{fig:APAGapZOffsetUncorrected}
\newlabel{fig:APAGapZOffset}
\newlabel{fig:AtmosphericNeutrinoAnomaly}
\newlabel{fig:BetaDecayEnergy}
\newlabel{fig:ChargeHit}
\newlabel{fig:CoherentNoiseRemovalNoNoise}
\newlabel{fig:CoherentNoiseRemovalNoise}
\newlabel{fig:CoherentNoiseRemoval}
\newlabel{fig:CollectionPlaneNoise}
\newlabel{fig:DQMPlot1}
\newlabel{fig:DQMPlot2}
\newlabel{fig:DQMPlot3}
\newlabel{fig:DQMPlot4}
\newlabel{fig:DQMPlots}
\newlabel{fig:DUNE35ton}
\newlabel{fig:DUNEAppearanceProbabilities}
\newlabel{fig:DUNEBeamFluxesAntiNeutrino}
\newlabel{fig:DUNEBeamFluxesNeutrino}
\newlabel{fig:DUNEBeamFluxes}
\newlabel{fig:DUNEBeam}
\newlabel{fig:DUNECPViolationDeltaCP}
\newlabel{fig:DUNECPViolationTime}
\newlabel{fig:DUNECPViolation}
\newlabel{fig:DUNEDeltaM31Resolution}
\newlabel{fig:DUNEDualPhaseCRP}
\newlabel{fig:DUNEDualPhase}
\newlabel{fig:DUNEFarDetectorAPA}
\newlabel{fig:DUNEFarDetectorDesign}
\newlabel{fig:DUNEMassHierarchyDeltaCP}
\newlabel{fig:DUNEMassHierarchyTime}
\newlabel{fig:DUNEMassHierarchy}
\newlabel{fig:DUNENearDetector}
\newlabel{fig:DUNEOctantSensitivity}
\newlabel{fig:DUNEPhotonDetectorsAPA}
\newlabel{fig:DUNEPhotonDetectorsBar}
\newlabel{fig:DUNEPhotonDetectors}
\newlabel{fig:DUNETheta13Resolution}
\newlabel{fig:DUNETheta13}
\newlabel{fig:DUNETheta23Resolution}
\newlabel{fig:DUNETheta23}
\newlabel{fig:DUNE}
\newlabel{fig:DataCalorimetryShowerEnergy}
\newlabel{fig:DataCalorimetryThreshold1}
\newlabel{fig:DataCalorimetryThreshold2}
\newlabel{fig:DataCalorimetryThreshold3}
\newlabel{fig:DataCalorimetryThreshold}
\newlabel{fig:DataCalorimetrydEdx}
\newlabel{fig:DataMuon}
\newlabel{fig:DataPi0Candidate}
\newlabel{fig:DataRMSBadRun}
\newlabel{fig:DataRMSGoodRun}
\newlabel{fig:DataRMS}
\newlabel{fig:DataSimulationNoiseComparison}
\newlabel{fig:DistanceDriftTime}
\newlabel{fig:DriftVelocityDiffGeo}
\newlabel{fig:DriftVelocityDiffRes}
\newlabel{fig:DriftVelocityDiff}
\newlabel{fig:DriftVelocityGraph}
\newlabel{fig:DriftVelocity}
\newlabel{fig:EVDHookRaw}
\newlabel{fig:EVDHookReconstructed}
\newlabel{fig:EVDHook}
\newlabel{fig:EVD}
\newlabel{fig:ElectricFieldScintillationIonisation}
\newlabel{fig:ExtraCorrectionPlaneSpacing}
\newlabel{fig:ExtraCorrectionWire}
\newlabel{fig:ExtraCorrections}
\newlabel{fig:FDCryostats}
\newlabel{fig:FamousShowerReconstructed}
\newlabel{fig:FamousShower}
\newlabel{fig:GlobalFit}
\newlabel{fig:HighNoiseState}
\newlabel{fig:HitChargeInteraction}
\newlabel{fig:HitChargeNonInteraction}
\newlabel{fig:HitCharges}
\newlabel{fig:HitFindingU}
\newlabel{fig:HitFindingV}
\newlabel{fig:HitFindingZ}
\newlabel{fig:HitFinding}
\newlabel{fig:HitGapDistance}
\newlabel{fig:HitTimesAPA023}
\newlabel{fig:HitTimesAPA1}
\newlabel{fig:HitTimesAPAs}
\newlabel{fig:HitTimesFixed}
\newlabel{fig:HitTimesFrame}
\newlabel{fig:HitTimesMC}
\newlabel{fig:HitTimesRange}
\newlabel{fig:HitTimesZoom}
\newlabel{fig:HitTimes}
\newlabel{fig:LAPDElectronLifetime}
\newlabel{fig:LAPDGasCirculation}
\newlabel{fig:LAPDLiquidCirculation}
\newlabel{fig:LAPDPistonPurgeImpurities}
\newlabel{fig:LAPDPistonPurgeSchematic}
\newlabel{fig:LAPDPistonPurge}
\newlabel{fig:LAPD}
\newlabel{fig:LArSoftStructure}
\newlabel{fig:LArTPCOperation1}
\newlabel{fig:LArTPCOperation2}
\newlabel{fig:LArTPCOperation3}
\newlabel{fig:LArTPCOperation4}
\newlabel{fig:LArTPCOperation}
\newlabel{fig:LEPZ0Resonance}
\newlabel{fig:LongBoPurity}
\newlabel{fig:LongBo}
\newlabel{fig:MTSResults}
\newlabel{fig:MTS}
\newlabel{fig:MassHierarchy}
\newlabel{fig:MatterEffectsCC}
\newlabel{fig:MatterEffectsNC}
\newlabel{fig:MatterEffects}
\newlabel{fig:MeshHits}
\newlabel{fig:NeutrinoPlatform}
\newlabel{fig:NoiseCorrelation}
\newlabel{fig:NoiseStates}
\newlabel{fig:NormalNoiseState}
\newlabel{fig:NygrenTPC}
\newlabel{fig:OnlineMonitoringFramework}
\newlabel{fig:PurityMonitor}
\newlabel{fig:ReconstructionWorkflow}
\newlabel{fig:RubbiaLArTPC}
\newlabel{fig:SimulationMuon}
\newlabel{fig:SolarNeutrinoCycles}
\newlabel{fig:SolarNeutrinoFluxes}
\newlabel{fig:StuckBitInterpolation}
\newlabel{fig:StuckBitWaveformStuck}
\newlabel{fig:StuckBitWaveformUnstuck}
\newlabel{fig:StuckBitWaveform}
\newlabel{fig:SuperKamiokandeDirection}
\newlabel{fig:SuperKamiokandeLE}
\newlabel{fig:TPC5TPC7GapAngle}
\newlabel{fig:TPC5TPC7GapFit}
\newlabel{fig:TPC5TPC7Gap}
\newlabel{fig:TPC5TPC7XOffsetZOffset}
\newlabel{fig:TPC5TPC7XOff}
\newlabel{fig:TPC5TPC7ZOff}
\newlabel{fig:TPCCounterOffset}
\newlabel{fig:TPCCounterT0CorrectionCounter}
\newlabel{fig:TPCCounterT0CorrectionTPC}
\newlabel{fig:TPCCounterT0Correction}
\newlabel{fig:TPCCounterT0DifferenceDataResidual}
\newlabel{fig:TPCCounterT0DifferenceData}
\newlabel{fig:TPCCounterT0DifferenceMC}
\newlabel{fig:TPCCounterT0Difference}
\newlabel{fig:TPCPhotonT0Difference}
\newlabel{fig:TrackMisalignmentCollectionSpacingGeo}
\newlabel{fig:TrackMisalignmentCollectionSpacingRes}
\newlabel{fig:TrackMisalignmentCollectionSpacing}
\newlabel{fig:TrackMisalignmentDriftVelocityGeo}
\newlabel{fig:TrackMisalignmentDriftVelocityRes}
\newlabel{fig:TrackMisalignmentDriftVelocity}
\newlabel{fig:TrackMisalignmentZPositionGeo}
\newlabel{fig:TrackMisalignmentZPositionRes}
\newlabel{fig:TrackMisalignmentZPosition}
\newlabel{fig:TrackMisalignment}
\newlabel{fig:TrackSelectionBefore}
\newlabel{fig:TrackSelectionCounterShadow}
\newlabel{fig:TrackSelectionFinal}
\newlabel{fig:TrackSelection}
\newlabel{fig:TwoPeakAmbiguity}
\newlabel{fig:WebInterface}
\newlabel{fig:WebPage}
\newlabel{fig:evd_crossing}
\newlabel{fig:evd_gap}
\newlabel{fig:lbne-artdaq}
\newlabel{sec:35tonCameraSystemOperation}
\newlabel{sec:35tonCameraSystem}
\newlabel{sec:35tonCryostat}
\newlabel{sec:35tonDAQ}
\newlabel{sec:35tonDataAcquisition}
\newlabel{sec:35tonDataFormats}
\newlabel{sec:35tonDataSummary}
\newlabel{sec:35tonDetector}
\newlabel{sec:35tonElectronicsReadout}
\newlabel{sec:35tonExternalCounters}
\newlabel{sec:35tonFilling}
\newlabel{sec:35tonPhaseIIOutcomesCryostatTPC}
\newlabel{sec:35tonPhaseIIOutcomesDAQ}
\newlabel{sec:35tonPhaseIIOutcomesNoise}
\newlabel{sec:35tonPhaseIIOutcomesTriggeringSystems}
\newlabel{sec:35tonPhaseIIOutcomes}
\newlabel{sec:35tonPhaseIIRun}
\newlabel{sec:35tonPhaseII}
\newlabel{sec:35tonPhaseIOutcomes}
\newlabel{sec:35tonPhaseI}
\newlabel{sec:35tonPhotonDetectors}
\newlabel{sec:35tonSummary}
\newlabel{sec:35tonTPC}
\newlabel{sec:35ton}
\newlabel{sec:APACrossingAlignment}
\newlabel{sec:APACrossingCharge}
\newlabel{sec:APACrossingDriftComparison}
\newlabel{sec:APACrossingMisalignment}
\newlabel{sec:APACrossingT0}
\newlabel{sec:APACrossing}
\newlabel{sec:APAGapCharge}
\newlabel{sec:APAGapCrossing}
\newlabel{sec:APAGapOffsets}
\newlabel{sec:APAOffsetMeasurements}
\newlabel{sec:AtmosphericNeutrinoAnomaly}
\newlabel{sec:AutomatedDataTransfer}
\newlabel{sec:BLM}
\newlabel{sec:BlurredCluster}
\newlabel{sec:CPViolation}
\newlabel{sec:Calorimetry}
\newlabel{sec:CombinedOffsets}
\newlabel{sec:CounterMonitoring}
\newlabel{sec:CurrentExperiments}
\newlabel{sec:DQMPlots}
\newlabel{sec:DQM}
\newlabel{sec:DUNEBeam}
\newlabel{sec:DUNEDualPhase}
\newlabel{sec:DUNEExperiment}
\newlabel{sec:DUNEMassHierarchyCPViolation}
\newlabel{sec:DUNEOscillationParameters}
\newlabel{sec:DUNEOtherPhysics}
\newlabel{sec:DUNEOverview}
\newlabel{sec:DUNEPhysics}
\newlabel{sec:DUNESinglePhase}
\newlabel{sec:DataCalorimetryReconstruction}
\newlabel{sec:DataPi0Reconstruction}
\newlabel{sec:DataShowerReconstruction}
\newlabel{sec:DataSpecificReconstruction}
\newlabel{sec:EMShower}
\newlabel{sec:EnergyDetermination}
\newlabel{sec:EventDisplay}
\newlabel{sec:EvidenceNeutrinoOscillations}
\newlabel{sec:FarDetector}
\newlabel{sec:FillingLAPD}
\newlabel{sec:FilterRegeneration}
\newlabel{sec:GeneralMonitoring}
\newlabel{sec:HistoricalContext}
\newlabel{sec:HitReconstruction}
\newlabel{sec:HookEVDs}
\newlabel{sec:ImprovingDataQuality}
\newlabel{sec:InteractionTimeHits}
\newlabel{sec:KamLAND}
\newlabel{sec:LAPDExperimentalSetup}
\newlabel{sec:LAPDOutcomes}
\newlabel{sec:LAPD}
\newlabel{sec:LArPuritySingleTrack}
\newlabel{sec:LArSoft}
\newlabel{sec:LArTPCChallenges}
\newlabel{sec:LArTPCHistory}
\newlabel{sec:LArTPCOperation}
\newlabel{sec:LArTPC}
\newlabel{sec:LongBo}
\newlabel{sec:MTSLAPD}
\newlabel{sec:MTS}
\newlabel{sec:MatterEffects}
\newlabel{sec:MeasuringAPAGaps}
\newlabel{sec:MonitoringFrameworkDesign}
\newlabel{sec:NND}
\newlabel{sec:NearDetector}
\newlabel{sec:NeutrinoMass}
\newlabel{sec:NeutrinoOscillations}
\newlabel{sec:NeutrinoPhysicsStatus}
\newlabel{sec:ObjectReconstruction}
\newlabel{sec:OnlineMonitoring}
\newlabel{sec:OscillationParameters}
\newlabel{sec:PhotonMonitoring}
\newlabel{sec:Preparing35tonData}
\newlabel{sec:ProtoDUNE}
\newlabel{sec:PurityAnalysis}
\newlabel{sec:PurityMonitoring}
\newlabel{sec:ReconstructingMuonTracks}
\newlabel{sec:ReconstructionChain}
\newlabel{sec:ReconstructionPerformance}
\newlabel{sec:RoadToDUNE}
\newlabel{sec:SNO}
\newlabel{sec:SelectingEVDData}
\newlabel{sec:SelectingTheData}
\newlabel{sec:SheffieldCameras}
\newlabel{sec:ShowerData}
\newlabel{sec:ShowerEnergy}
\newlabel{sec:ShowerReconstruction}
\newlabel{sec:ShowersOverview}
\newlabel{sec:SimulatedData}
\newlabel{sec:SuperKamiokande}
\newlabel{sec:TPCMonitoring}
\newlabel{sec:TrackShowerSeparation}
\newlabel{sec:VacuumOscillations}
\newlabel{sec:WebInterface}
\newlabel{sec:WebPage}
\newlabel{sec:WritingMonitoringData}
\newlabel{sec:lbne-artdaq}
\newlabel{sub@fig:2DnumuCCClusters}
\newlabel{sub@fig:2DnumuCCHits}
\newlabel{sub@fig:35tonCameraPhoto}
\newlabel{sub@fig:35tonCameraSchematic}
\newlabel{sub@fig:35tonGasFilling}
\newlabel{sub@fig:35tonLiquidFilling}
\newlabel{sub@fig:3DnumuCC2D}
\newlabel{sub@fig:3DnumuCC3D}
\newlabel{sub@fig:APACrossingAligmentLeastSqResidual}
\newlabel{sub@fig:APACrossingAligmentLeastSqSeparation}
\newlabel{sub@fig:APACrossingAlignmentLeastSqMin}
\newlabel{sub@fig:APACrossingAlignmentSeparationMin}
\newlabel{sub@fig:APAGapMCXOffsetZOffsetAngle}
\newlabel{sub@fig:APAGapMCXOffsetZOffsetAngle}
\newlabel{sub@fig:APAGapMCXOffsetZOffset}
\newlabel{sub@fig:APAGapMCXOffsetZOffset}
\newlabel{sub@fig:APAGapMCZOffset}
\newlabel{sub@fig:APAGapMCZOffset}
\newlabel{sub@fig:APAGapXOffsetNegFix}
\newlabel{sub@fig:APAGapXOffsetNeg}
\newlabel{sub@fig:APAGapXOffsetPosFix}
\newlabel{sub@fig:APAGapXOffsetPos}
\newlabel{sub@fig:APAGapXOffsetZOffsetNegFix}
\newlabel{sub@fig:APAGapXOffsetZOffsetNeg}
\newlabel{sub@fig:APAGapXOffsetZOffsetPosFix}
\newlabel{sub@fig:APAGapXOffsetZOffsetPos}
\newlabel{sub@fig:APAGapZOffsetCorrected}
\newlabel{sub@fig:APAGapZOffsetUncorrected}
\newlabel{sub@fig:CoherentNoiseRemovalNoNoise}
\newlabel{sub@fig:CoherentNoiseRemovalNoise}
\newlabel{sub@fig:DQMPlot1}
\newlabel{sub@fig:DQMPlot2}
\newlabel{sub@fig:DQMPlot3}
\newlabel{sub@fig:DQMPlot4}
\newlabel{sub@fig:DUNEBeamFluxesAntiNeutrino}
\newlabel{sub@fig:DUNEBeamFluxesNeutrino}
\newlabel{sub@fig:DUNECPViolationDeltaCP}
\newlabel{sub@fig:DUNECPViolationTime}
\newlabel{sub@fig:DUNEDeltaM31Resolution}
\newlabel{sub@fig:DUNEMassHierarchyDeltaCP}
\newlabel{sub@fig:DUNEMassHierarchyTime}
\newlabel{sub@fig:DUNEOctantSensitivity}
\newlabel{sub@fig:DUNEPhotonDetectorsAPA}
\newlabel{sub@fig:DUNEPhotonDetectorsBar}
\newlabel{sub@fig:DUNETheta13Resolution}
\newlabel{sub@fig:DUNETheta23Resolution}
\newlabel{sub@fig:DataCalorimetryThreshold1}
\newlabel{sub@fig:DataCalorimetryThreshold2}
\newlabel{sub@fig:DataCalorimetryThreshold3}
\newlabel{sub@fig:DataMuon}
\newlabel{sub@fig:DataRMSBadRun}
\newlabel{sub@fig:DataRMSGoodRun}
\newlabel{sub@fig:DistanceDriftTime}
\newlabel{sub@fig:DriftVelocityDiffGeo}
\newlabel{sub@fig:DriftVelocityDiffRes}
\newlabel{sub@fig:DriftVelocityGraph}
\newlabel{sub@fig:EVDHookRaw}
\newlabel{sub@fig:EVDHookReconstructed}
\newlabel{sub@fig:ExtraCorrectionPlaneSpacing}
\newlabel{sub@fig:ExtraCorrectionWire}
\newlabel{sub@fig:HighNoiseState}
\newlabel{sub@fig:HitChargeInteraction}
\newlabel{sub@fig:HitChargeNonInteraction}
\newlabel{sub@fig:HitFindingU}
\newlabel{sub@fig:HitFindingV}
\newlabel{sub@fig:HitFindingZ}
\newlabel{sub@fig:HitTimesAPA023}
\newlabel{sub@fig:HitTimesAPA1}
\newlabel{sub@fig:HitTimesRange}
\newlabel{sub@fig:HitTimesZoom}
\newlabel{sub@fig:LAPDPistonPurgeImpurities}
\newlabel{sub@fig:LAPDPistonPurgeSchematic}
\newlabel{sub@fig:LArTPCOperation1}
\newlabel{sub@fig:LArTPCOperation2}
\newlabel{sub@fig:LArTPCOperation3}
\newlabel{sub@fig:LArTPCOperation4}
\newlabel{sub@fig:MatterEffectsCC}
\newlabel{sub@fig:MatterEffectsNC}
\newlabel{sub@fig:NormalNoiseState}
\newlabel{sub@fig:SimulationMuon}
\newlabel{sub@fig:StuckBitWaveformStuck}
\newlabel{sub@fig:StuckBitWaveformUnstuck}
\newlabel{sub@fig:TPC5TPC7GapAngle}
\newlabel{sub@fig:TPC5TPC7Gap}
\newlabel{sub@fig:TPCCounterT0CorrectionCounter}
\newlabel{sub@fig:TPCCounterT0CorrectionTPC}
\newlabel{sub@fig:TPCCounterT0DifferenceDataResidual}
\newlabel{sub@fig:TPCCounterT0DifferenceData}
\newlabel{sub@fig:TPCCounterT0DifferenceMC}
\newlabel{sub@fig:TrackMisalignmentCollectionSpacingGeo}
\newlabel{sub@fig:TrackMisalignmentCollectionSpacingRes}
\newlabel{sub@fig:TrackMisalignmentDriftVelocityGeo}
\newlabel{sub@fig:TrackMisalignmentDriftVelocityRes}
\newlabel{sub@fig:TrackMisalignmentZPositionGeo}
\newlabel{sub@fig:TrackMisalignmentZPositionRes}
\newlabel{sub@fig:TrackSelectionBefore}
\newlabel{sub@fig:TrackSelectionCounterShadow}
\newlabel{sub@fig:TrackSelectionFinal}
\newlabel{tab:35tonCryostat}
\newlabel{tab:APAGaps}
\newlabel{tab:APAOffsets}
\newlabel{tab:DUNEExposure}
\newlabel{tab:NobleProperties}
\newlabel{tab:OscillationParameters}
