\addvspace {10\p@ }
\addvspace {10\p@ }
\contentsline {figure}{\numberline {2.1}{\ignorespaces Energy spectrum of the electron produced in beta decay.}}{4}{figure.caption.7}
\contentsline {figure}{\numberline {2.2}{\ignorespaces Measurements of the hadron production cross-section around the Z resonance.}}{7}{figure.caption.8}
\contentsline {figure}{\numberline {2.3}{\ignorespaces Solar neutrino energy spectra as predicted by the Standard Solar Model \cite {Bahcall2005}. The solid lines represent neutrinos produced during the p-p chain and dashed line represent neutrinos from the CNO cycle. Each spectrum illustrates a particular reaction during the process of a given chain.\relax }}{8}{figure.caption.9}
\contentsline {figure}{\numberline {2.4}{\ignorespaces The double ratio \textit {R} of muon to electron neutrino events showing data divided by expectation \cite {Mann1999}. Various underground atmospheric neutrino detectors are shown.\relax }}{10}{figure.caption.10}
\contentsline {figure}{\numberline {2.5}{\ignorespaces Zenith angle distributions of $\mu $-like and $e$-like events for sub-GeV and multi-GeV data sets. Upward-going particles have $\qopname \relax o{cos}{\Theta } < 0$ and downward-going particles have $\qopname \relax o{cos}{\Theta } > 0$. The hatched region shows the Monte Carlo expectation for no oscillations and the bold line is the best-fit expectation for $\nu _{\mu }\rightarrow \nu _{\tau }$ oscillations. Taken from \cite {SuperKamiokande1998}.\relax }}{12}{figure.caption.11}
\contentsline {figure}{\numberline {2.6}{\ignorespaces The ratio of the number of data events to Monte Carlo events in the absence of oscillations as a function of reconstructed $L/E_{\nu }$. The dashed lines show the expected shape for $\nu _{\mu }\rightarrow \nu _{\tau }$ oscillations. Taken from \cite {SuperKamiokande1998}.\relax }}{12}{figure.caption.12}
\contentsline {figure}{\numberline {2.7}{\ignorespaces Comparison of the predictions of the neutrino fluxes from the Standard Solar Model with measured rates from a variety of solar neutrino experiments. The results of SNO (D$_2$O target, right two comparisons) show that the expected flux is observed, but not necessarily as electron neutrinos. This shows conclusively the oscillatory nature of neutrinos.\relax }}{14}{figure.caption.13}
\contentsline {figure}{\numberline {2.8}{\ignorespaces General scattering mechanics which occur as neutrinos pass through matter. Neutral current scattering (Figure\nobreakspace {}\ref {fig:MatterEffectsNC}) occurs for all neutrino flavour combinations whereas charged current scattering (Figure\nobreakspace {}\ref {fig:MatterEffectsCC}) only occurs when the incoming leptons have the same flavour.\relax }}{18}{figure.caption.14}
\contentsline {figure}{\numberline {2.9}{\ignorespaces Global 3-neutrino oscillation analysis taken from \cite {NuFit2014,NuFit2017}. Each panel shows the two-dimensional projection of the allowed six-dimensional region after marginalisation with respect to the undisplayed parameters. The different contours correspond to 1$\sigma $, 90\%, 2$\sigma $, 99\%, 3$\sigma $ CL (2 dof).\relax }}{21}{figure.caption.15}
\contentsline {figure}{\numberline {2.10}{\ignorespaces Demonstration of the current uncertainties in the neutrino mass.}}{23}{figure.caption.17}
\addvspace {10\p@ }
\contentsline {figure}{\numberline {3.1}{\ignorespaces Cartoon showing the configuration of the Deep Underground Neutrino Experiment.}}{26}{figure.caption.18}
\contentsline {figure}{\numberline {3.2}{\ignorespaces Original TPC design, Nygren (1974)}}{27}{figure.caption.19}
\contentsline {figure}{\numberline {3.3}{\ignorespaces First LArTPC detector, Rubbia (1977)}}{28}{figure.caption.21}
\contentsline {figure}{\numberline {3.4}{\ignorespaces Effect of electric field on luminosity of ionisation electrons and scintillation light in a LArTPC.}}{30}{figure.caption.22}
\contentsline {figure}{\numberline {3.5}{\ignorespaces Schematic demonstrating the basic operational principles of a LArTPC.}}{31}{figure.caption.23}
\contentsline {figure}{\numberline {3.6}{\ignorespaces Demonstration of how having access to multiple oscillation maxima facilitates measurements of both the neutrino mass hierarchy and leptonic CP violation using the same experiment.}}{34}{figure.caption.24}
\contentsline {figure}{\numberline {3.7}{\ignorespaces Longitudinal section of the LBNF beamline facility at Fermilab \cite {DUNECDR3}.\relax }}{35}{figure.caption.25}
\contentsline {figure}{\numberline {3.8}{\ignorespaces The fluxes of the different neutrino flavour components of the DUNE beam in neutrino and antineutrino running mode.}}{36}{figure.caption.26}
\contentsline {figure}{\numberline {3.9}{\ignorespaces The layout of the four cryostats underground at SURF comprising the DUNE far detector.}}{37}{figure.caption.27}
\contentsline {figure}{\numberline {3.10}{\ignorespaces The basic design of a single-phase DUNE far detector module.}}{38}{figure.caption.28}
\contentsline {figure}{\numberline {3.11}{\ignorespaces Design of a DUNE far detector Anode Plane Assembly (APA).}}{39}{figure.caption.29}
\contentsline {figure}{\numberline {3.12}{\ignorespaces The design of the photon detectors for the DUNE far detector.}}{41}{figure.caption.30}
\contentsline {figure}{\numberline {3.13}{\ignorespaces The DUNE dual-phase detector (partially open).}}{42}{figure.caption.31}
\contentsline {figure}{\numberline {3.14}{\ignorespaces The extraction, amplification and readout of the ionisation electrons through the gaseous argon phase in the DUNE dual-phase LArTPC design.}}{42}{figure.caption.32}
\contentsline {figure}{\numberline {3.15}{\ignorespaces Schematic of the DUNE near neutrino detector fine-grained tracker design.}}{44}{figure.caption.33}
\contentsline {figure}{\numberline {3.16}{\ignorespaces The appearance probability at a baseline of 1300\nobreakspace {}km, as a function of neutrino energy, for $\delta _{CP}=-\pi /2$ (blue), 0 (red) and $\pi /2$ (green) for neutrinos (left) and antineutrinos (right), for normal hierarchy. The black lines indicates the oscillation probability if $\theta _{13}$ were equal to zero. Taken from \cite {DUNECDR2}.\relax }}{47}{figure.caption.35}
\contentsline {figure}{\numberline {3.17}{\ignorespaces Sensitivity of the DUNE experiment to the neutrino mass hierarchy.}}{48}{figure.caption.36}
\contentsline {figure}{\numberline {3.18}{\ignorespaces Sensitivity of the DUNE experiment to leptonic CP violation.}}{50}{figure.caption.37}
\contentsline {figure}{\numberline {3.19}{\ignorespaces The sensitivity of DUNE to the octant and value of $\theta _{23}$.}}{51}{figure.caption.38}
\contentsline {figure}{\numberline {3.20}{\ignorespaces The sensitivity of DUNE to the oscillation parameters describing $\nu _e$ and $\bar {\nu }_e$ appearance.}}{52}{figure.caption.39}
\contentsline {figure}{\numberline {3.21}{\ignorespaces The 35\nobreakspace {}ton cryostat and detector designed to prototype the DUNE far detector design.}}{54}{figure.caption.40}
\contentsline {figure}{\numberline {3.22}{\ignorespaces Schematic showing the layout of the ProtoDUNEs at the CERN neutrino platform.}}{55}{figure.caption.41}
\addvspace {10\p@ }
\contentsline {figure}{\numberline {4.1}{\ignorespaces The Materials Test Stand Stand at FNAL.}}{59}{figure.caption.42}
\contentsline {figure}{\numberline {4.2}{\ignorespaces Results from the Materials Test Stand showing the water contamination in LAr and the corresponding electron lifetime.}}{60}{figure.caption.43}
\contentsline {figure}{\numberline {4.3}{\ignorespaces Schematic design of the purity monitors utilised at the FNAL LAr test stands.}}{61}{figure.caption.44}
\contentsline {figure}{\numberline {4.4}{\ignorespaces The Liquid Argon Purity Demonstrator cryostat and purification system.}}{63}{figure.caption.45}
\contentsline {figure}{\numberline {4.5}{\ignorespaces The piston purge technique in the Liquid Argon Purity Demonstrator to remove atmospheric impurities before filling.}}{64}{figure.caption.46}
\contentsline {figure}{\numberline {4.6}{\ignorespaces The concentration of electronegative impurities during the gas circulation stage in the Liquid Argon Purity Demonstrator following the piston purge.}}{65}{figure.caption.47}
\contentsline {figure}{\numberline {4.7}{\ignorespaces Schematic showing the recirculation of the LAr during commissioning and operations of the Liquid Argon Purity Demonstrator.}}{66}{figure.caption.48}
\contentsline {figure}{\numberline {4.8}{\ignorespaces The electron lifetime achieved in the Liquid Argon Purity Demonstrator during a six week run.}}{67}{figure.caption.49}
\contentsline {figure}{\numberline {4.9}{\ignorespaces The LongBo TPC detector shown within the Liquid Argon Purity Demonstrator Cryostat.}}{68}{figure.caption.50}
\contentsline {figure}{\numberline {4.10}{\ignorespaces The LAr purity within the Liquid Argon Purity Demonstrator cryostat with the LongBo TPC present, measured using both data from the detector and information from the purity monitors.}}{68}{figure.caption.51}
\contentsline {figure}{\numberline {4.11}{\ignorespaces The 35\nobreakspace {}ton cryostat.}}{70}{figure.caption.52}
\contentsline {figure}{\numberline {4.12}{\ignorespaces The network linking the 35\nobreakspace {}ton cryostat, the Liquid Argon Purity Demonstrator and the purification system at PC4, Fermilab.}}{71}{figure.caption.54}
\contentsline {figure}{\numberline {4.13}{\ignorespaces Filling the 35\nobreakspace {}ton cryostat in four stages: piston purge, gas recirculation, cooldown and liquid filling.}}{72}{figure.caption.55}
\contentsline {figure}{\numberline {4.14}{\ignorespaces The electron lifetime in the 35\nobreakspace {}ton cryostat measured by two purity monitors over the course of the two month Phase\nobreakspace {}I run.}}{73}{figure.caption.56}
\contentsline {figure}{\numberline {4.15}{\ignorespaces The 35\nobreakspace {}ton detector operated during Phase\nobreakspace {}II of the 35\nobreakspace {}ton program.}}{75}{figure.caption.57}
\contentsline {figure}{\numberline {4.16}{\ignorespaces Photograph of the partially installed 35\nobreakspace {}ton detector.}}{76}{figure.caption.58}
\contentsline {figure}{\numberline {4.17}{\ignorespaces The 35\nobreakspace {}ton TPC geometry.}}{77}{figure.caption.59}
\contentsline {figure}{\numberline {4.18}{\ignorespaces Photon detector units as implemented within the 35\nobreakspace {}ton APAs.}}{78}{figure.caption.60}
\contentsline {figure}{\numberline {4.19}{\ignorespaces The location of the external counters positioned around the outer walls and in the ceiling above the 35\nobreakspace {}ton cryostat.}}{79}{figure.caption.61}
\contentsline {figure}{\numberline {4.20}{\ignorespaces Block diagram showing the triggering system for the 35\nobreakspace {}ton Phase\nobreakspace {}II.}}{81}{figure.caption.62}
\contentsline {figure}{\numberline {4.21}{\ignorespaces 35\nobreakspace {}ton data format}}{82}{figure.caption.63}
\contentsline {figure}{\numberline {4.22}{\ignorespaces Demonstration of how TPC data from a triggered event in a LArTPC is saved when employing a DAQ with continuous readout}}{84}{figure.caption.64}
\contentsline {figure}{\numberline {4.23}{\ignorespaces The \textit {lbne-artdaq} framework}}{85}{figure.caption.65}
\contentsline {figure}{\numberline {4.24}{\ignorespaces The calibration images for the 8 cameras in the system. Upper (left to right): phase separator, ullage, cathode top right, cathode bottom right. Lower (left to right) cooldown sprayers, cathode top left, cathode bottom left and high voltage feedthrough. The upper images were taken with a halogen light illuminating the cryostat, prior to it being sealed up. The lower images were taken with the LED ring light on, with the cryostat sealed up. All images are left-right inverted due to software. Taken from \cite {35tonCameras2017}.\relax }}{87}{figure.caption.66}
\contentsline {figure}{\numberline {4.25}{\ignorespaces An example camera module developed for the 35\nobreakspace {}ton Sheffield camera system.}}{88}{figure.caption.67}
\contentsline {figure}{\numberline {4.26}{\ignorespaces Two camera modules mounted on cryo piping in the 35\nobreakspace {}ton cryostat.}}{89}{figure.caption.68}
\contentsline {figure}{\numberline {4.27}{\ignorespaces Full system block diagram for the camera modules in the DUNE 35\nobreakspace {}ton prototype.}}{89}{figure.caption.69}
\contentsline {figure}{\numberline {4.28}{\ignorespaces The variation in picture quality degradation in the 35\nobreakspace {}ton camera system is illustrated by the changes in Camera\nobreakspace {}1 and Camera\nobreakspace {}4 over time.}}{90}{figure.caption.70}
\contentsline {figure}{\numberline {4.29}{\ignorespaces The broken pipe, originally part of the framework introducing gaseous argon from LAPD into the 35\nobreakspace {}ton to maintain LAr levels, which resulted in the poisoning of the whole LAr volume by allowing the introduction of air into the system.}}{92}{figure.caption.71}
\contentsline {figure}{\numberline {4.30}{\ignorespaces The data taking period of the 35\nobreakspace {}ton Phase\nobreakspace {}II experiment.}}{93}{figure.caption.72}
\contentsline {figure}{\numberline {4.31}{\ignorespaces Event display depicting the charge deposited by an electromagnetic shower during the 35\nobreakspace {}ton Phase\nobreakspace {}II run.}}{94}{figure.caption.73}
\contentsline {figure}{\numberline {4.32}{\ignorespaces Difference between optical hit peak times and muon counter trigger times for photon detector 3 in the 35\nobreakspace {}ton photon detection system.}}{97}{figure.caption.74}
\contentsline {figure}{\numberline {4.33}{\ignorespaces Average Optical Hit Amplitude per Event vs. Counter Pair Positions for the 35\nobreakspace {}ton photon detection system.}}{97}{figure.caption.74}
\contentsline {figure}{\numberline {4.34}{\ignorespaces Comparison between example muons tracks observed in 35\nobreakspace {}ton data and simulation, along with example waveforms for randomly selected channels.}}{98}{figure.caption.75}
\contentsline {figure}{\numberline {4.35}{\ignorespaces FFT of ADC values for RCE00 for two different noise states.}}{99}{figure.caption.76}
\contentsline {figure}{\numberline {4.36}{\ignorespaces The correlation between waveforms recorded on different channel combinations for all 2048 35\nobreakspace {}ton channels.}}{100}{figure.caption.77}
\addvspace {10\p@ }
\contentsline {figure}{\numberline {5.1}{\ignorespaces The LArSoft architecture, highlighting support for both common and experiment-specific algorithms and methods and the interfacing with other packages.}}{104}{figure.caption.78}
\contentsline {figure}{\numberline {5.2}{\ignorespaces The LArSoft reconstruction workflow to produce 3D reconstructed objects from the raw charge read out by the anode wires.}}{106}{figure.caption.79}
\contentsline {figure}{\numberline {5.3}{\ignorespaces Detector response for charge readout in a LArTPC.}}{107}{figure.caption.80}
\contentsline {figure}{\numberline {5.4}{\ignorespaces The process of deconvolution and hit finding to determine the correct charge from the measured pulses on the readout wires.}}{107}{figure.caption.81}
\contentsline {figure}{\numberline {5.5}{\ignorespaces Demonstration of 2D reconstruction in LArSoft on a simulated $\nu _{\mu }$CC event.}}{108}{figure.caption.82}
\contentsline {figure}{\numberline {5.6}{\ignorespaces Demonstration of 3D reconstruction in LArSoft on a simulated $\nu _{\mu }$CC event.}}{109}{figure.caption.83}
\contentsline {figure}{\numberline {5.7}{\ignorespaces Correlation between the true deposited energy in an electromagnetic shower and the total charge in the detector for electron showers in the DUNE far detector.}}{111}{figure.caption.84}
\contentsline {figure}{\numberline {5.8}{\ignorespaces An example particle gun $\pi ^0$ event in the 35\nobreakspace {}ton geometry.}}{113}{figure.caption.85}
\contentsline {figure}{\numberline {5.9}{\ignorespaces A example 2D Gaussian kernel alongside the contributions from each dimension.}}{114}{figure.caption.86}
\contentsline {figure}{\numberline {5.10}{\ignorespaces Simplified demonstration, in 1D, of the blurring process used when smearing charge from a hit map.}}{116}{figure.caption.87}
\contentsline {figure}{\numberline {5.11}{\ignorespaces The output of the blurring stage of the BlurredCluster algorithm on the hit maps from two planes of the 35\nobreakspace {}ton $\pi ^0$ event illustrated in Figure\nobreakspace {}\ref {fig:pi0Showers}.}}{116}{figure.caption.88}
\contentsline {figure}{\numberline {5.12}{\ignorespaces The 2D clusters made using BlurredCluster when applied to the 35\nobreakspace {}ton $\pi ^0$ event shown in Figure\nobreakspace {}\ref {fig:pi0Showers}.}}{117}{figure.caption.89}
\contentsline {figure}{\numberline {5.13}{\ignorespaces Demonstration of the `global wire' concept in single-phase LArTPC reconstruction.}}{118}{figure.caption.90}
\contentsline {figure}{\numberline {5.14}{\ignorespaces Comparison of the 2D shower cluster reconstruction and the 3D tracking reconstruction for a 35\nobreakspace {}ton $\pi ^0$ event.}}{119}{figure.caption.91}
\contentsline {figure}{\numberline {5.15}{\ignorespaces Demonstration of the method utilised to ensure a correct shower orientation of the shower in a given view for the purpose of shower start finding in the EMShower algorithm.}}{121}{figure.caption.92}
\contentsline {figure}{\numberline {5.16}{\ignorespaces The output from the full 3D shower reconstruction provided by BlurredCluster/EMShower when applied to the 35\nobreakspace {}ton $\pi ^0$ event shown in Figure\nobreakspace {}\ref {fig:pi0Showers}.}}{122}{figure.caption.93}
\contentsline {figure}{\numberline {5.17}{\ignorespaces An example $\nu _e$CC interaction in the DUNE far detector.}}{123}{figure.caption.94}
\contentsline {figure}{\numberline {5.18}{\ignorespaces A simplified event topology demonstrated typical track and shower topologies.}}{124}{figure.caption.95}
\contentsline {figure}{\numberline {5.19}{\ignorespaces The result of applying the track/shower separation, BlurredCluster and EMShower algorithms to the example DUNE far detector $\nu _e$CC event demonstrated in Figure\nobreakspace {}\ref {fig:nueCC}.}}{125}{figure.caption.96}
\contentsline {figure}{\numberline {5.20}{\ignorespaces The fraction of total shower particles for which a shower object is created when using BlurredCluster/EMShower reconstruction.}}{127}{figure.caption.97}
\contentsline {figure}{\numberline {5.21}{\ignorespaces The difference between the true and reconstructed shower conversion points.}}{127}{figure.caption.98}
\contentsline {figure}{\numberline {5.22}{\ignorespaces The vector dot product between the true and reconstructed initial shower direction.}}{127}{figure.caption.98}
\contentsline {figure}{\numberline {5.23}{\ignorespaces The completeness of the reconstruction shower energy when compared with the true deposited energy from simulation.}}{128}{figure.caption.99}
\contentsline {figure}{\numberline {5.24}{\ignorespaces The dE/dx information from the start of the reconstructed shower object.}}{128}{figure.caption.99}
\contentsline {figure}{\numberline {5.25}{\ignorespaces The 35\nobreakspace {}ton fully reconstructed $\pi ^0$ invariant mass peak.}}{129}{figure.caption.100}
\contentsline {figure}{\numberline {5.26}{\ignorespaces The 35\nobreakspace {}ton $\pi ^0$ mass peak considered using a combination of reconstructed and truth information.}}{130}{figure.caption.101}
\contentsline {figure}{\numberline {5.27}{\ignorespaces Performance of the track/shower separation reconstruction by considering how well separated tracks and showers from the neutrino interaction vertex are and the quality of the reconstructed electron shower.}}{131}{figure.caption.102}
\contentsline {figure}{\numberline {5.28}{\ignorespaces The performance of the track/shower separation and shower reconstruction when applied to DUNE $\nu _e$CC far detector interactions.}}{131}{figure.caption.103}
\addvspace {10\p@ }
\contentsline {figure}{\numberline {6.1}{\ignorespaces The software framework designed and built for online monitoring during the 35\nobreakspace {}ton Phase\nobreakspace {}II run.}}{134}{figure.caption.104}
\contentsline {figure}{\numberline {6.2}{\ignorespaces Selection of figures made by the Data Quality Monitoring framework during 35\nobreakspace {}ton Phase\nobreakspace {}II running.}}{139}{figure.caption.105}
\contentsline {figure}{\numberline {6.3}{\ignorespaces Example online event display made by the Online Monitoring framework}}{142}{figure.caption.106}
\contentsline {figure}{\numberline {6.4}{\ignorespaces Schematic showing the interface between the online monitoring system and the web.}}{143}{figure.caption.107}
\contentsline {figure}{\numberline {6.5}{\ignorespaces Web page for online monitoring and event displays}}{144}{figure.caption.108}
\addvspace {10\p@ }
\contentsline {figure}{\numberline {7.1}{\ignorespaces `Good' and `bad' 35\nobreakspace {}ton runs}}{146}{figure.caption.109}
\contentsline {figure}{\numberline {7.2}{\ignorespaces Correcting for stuck codes in the 35\nobreakspace {}ton data}}{147}{figure.caption.110}
\contentsline {figure}{\numberline {7.3}{\ignorespaces Raw data stuck bit mitigation}}{148}{figure.caption.111}
\contentsline {figure}{\numberline {7.4}{\ignorespaces Coherent noise removal in 35\nobreakspace {}ton data}}{148}{figure.caption.112}
\contentsline {figure}{\numberline {7.5}{\ignorespaces Selecting tracks for 35\nobreakspace {}ton data analysis}}{150}{figure.caption.113}
\contentsline {figure}{\numberline {7.6}{\ignorespaces Demonstration of crossing muons tracks in the 35\nobreakspace {}ton TPC.}}{151}{figure.caption.114}
\contentsline {figure}{\numberline {7.7}{\ignorespaces Event display showing tracks passing across APA gaps and also through the APAs.}}{152}{figure.caption.115}
\contentsline {figure}{\numberline {7.8}{\ignorespaces Schematic showing an example APA gap-crossing track as viewed looking down from the top of the detector. The vertical direction represents the drift direction ($x$); the horizontal direction represents the $z$-direction. In general, these tracks make an angle with respect to the face of the APAs, as shown in the figure. As the gap in between the APAs is uninstrumented, no charge is deposited in this region.\relax }}{153}{figure.caption.116}
\contentsline {figure}{\numberline {7.9}{\ignorespaces Schematic showing an example track crossing two drift regions offset by an unknown quantity $\Delta z$. The effect of this is evident from the track deposits (Figure\nobreakspace {}\ref {fig:APAGapZOffsetUncorrected}) and can be corrected by ensuring the segments are aligned between the DVs (Figure\nobreakspace {}\ref {fig:APAGapZOffsetCorrected}).\relax }}{154}{figure.caption.117}
\contentsline {figure}{\numberline {7.10}{\ignorespaces Illustration of the eight gaps between the four APA frames.\relax }}{154}{figure.caption.118}
\contentsline {figure}{\numberline {7.11}{\ignorespaces The $z$-offset for the DV5/DV7 gap measured in the 35\nobreakspace {}ton data. A very noticeable double-peak structure is evident in Figure\nobreakspace {}\ref {fig:DV5DV7Gap}; this bias appears to be related to the sign of the angle the particle track makes to the APA planes.\relax }}{156}{figure.caption.119}
\contentsline {figure}{\numberline {7.12}{\ignorespaces Demonstration of how an $x$-offset in the positions of the APAs can explain the degeneracy evident in the $z$-offset measured using the 35\nobreakspace {}ton data (Figure\nobreakspace {}\ref {fig:DV5DV7XOffsetZOffset}). In the left-hand plots, Figures\nobreakspace {}\ref {fig:APAGapXOffsetPos} and\nobreakspace {}\ref {fig:APAGapXOffsetPosFix}, the through-going particle makes a positive angle to the face of the APAs and in the right-hand plots, Figures\nobreakspace {}\ref {fig:APAGapXOffsetNeg} and\nobreakspace {}\ref {fig:APAGapXOffsetNegFix}, the particle is travelling with a negative gradient. In both cases, the offset of the APAs in the $x$-direction is the same. It is clear from Figures\nobreakspace {}\ref {fig:APAGapXOffsetPosFix} and\nobreakspace {}\ref {fig:APAGapXOffsetNegFix} how the sign of the measured $\Delta z$ is dependent on the angle of the track.\relax }}{157}{figure.caption.120}
\contentsline {figure}{\numberline {7.13}{\ignorespaces Studies of the effects of offsets in the positions of the APAs in simulation. Artificial $z$- and $x$- offsets are introduced and their impact observed in the measurements of $\Delta z$. Figure\nobreakspace {}\ref {fig:APAGapMCZOffset} shows the effect of an offset in the $z$-direction; as expected, there is a single peak measuring the input value. Figures\nobreakspace {}\ref {fig:APAGapMCXOffsetZOffset} and\nobreakspace {}\ref {fig:APAGapMCXOffsetZOffsetAngle} show the consequence of offsets in both the $x$- and $z$-directions. This appears to show exactly what is seen in the 35\nobreakspace {}ton data (Figure\nobreakspace {}\ref {fig:DV5DV7XOffsetZOffset}).\relax }}{158}{figure.caption.121}
\contentsline {figure}{\numberline {7.14}{\ignorespaces {\color {red} Same as previous page -- which is better? I prefer the layout of the previous page but I like this one because you can see the 2cm offset in line with each other down the page!} Studies of the effects of offsets in the positions of the APAs in simulation. Artificial $z$- and $x$- offsets are introduced and their impact observed in the measurements of $\Delta z$. Figure\nobreakspace {}\ref {fig:APAGapMCZOffset} shows the effect of an offset in the $z$-direction; as expected, there is a single peak measuring the input value. Figures\nobreakspace {}\ref {fig:APAGapMCXOffsetZOffset} and\nobreakspace {}\ref {fig:APAGapMCXOffsetZOffsetAngle} show the consequence of offsets in both the $x$- and $z$-directions. This appears to show exactly what is seen in the 35\nobreakspace {}ton data (Figure\nobreakspace {}\ref {fig:DV5DV7XOffsetZOffset}).\relax }}{159}{figure.caption.122}
\contentsline {figure}{\numberline {7.15}{\ignorespaces The $\chi ^2$ distribution for all APA-gap traversing tracks in $\Delta z$-$\Delta x$ space.}}{160}{figure.caption.123}
\contentsline {figure}{\numberline {7.16}{\ignorespaces Demonstration of the effects of offsets in both the $x$- and $z$-directions in the determination of $\Delta z$ between DV5 and DV7. With an $x$-offset present, it is impossible for the true value of $\Delta z$ to be measured -- this is evident from Figure\nobreakspace {}\ref {fig:APAGapMC}. It is clear from these geometrical considerations how the measured offset $\Delta z_m$ will populate distributions either side of the true value; the true value $\Delta z$ is given by the minimum between the two distributions.\relax }}{161}{figure.caption.124}
\contentsline {figure}{\numberline {7.17}{\ignorespaces Extraction of the true value of $\Delta z$ from the full distribution of measured $z$-offsets. A measured value of $0.117\pm 0.007$\nobreakspace {}cm is found.\relax }}{162}{figure.caption.125}
\contentsline {figure}{\numberline {7.18}{\ignorespaces Measurement of the $x$-offset between DV5 and DV7 after applying the $z$-gap corrected determined using the method described in the text and Figure\nobreakspace {}\ref {fig:DV5DV7GapFit}. A measurement of $-0.286\pm 0.002$\nobreakspace {}cm is determined.\relax }}{162}{figure.caption.126}
\contentsline {figure}{\numberline {7.19}{\ignorespaces Measurement of the $z$-offset between DV5 and DV7 after applying the $x$-offset determined from Figure\nobreakspace {}\ref {fig:DV5DV7XOff}. As initially anticipated, there is a single peak distributed around the true value of the offset. This validates the method used and confirms the initial presence of an $x$-offset between the neighbouring APAs. The final measurement of $\Delta z$ is $0.103\pm 0.004$\nobreakspace {}cm which agrees reasonably with the value measured previously ($0.117\pm 0.007$\nobreakspace {}cm from Figure\nobreakspace {}\ref {fig:DV5DV7GapFit}).\relax }}{163}{figure.caption.127}
\contentsline {figure}{\numberline {7.20}{\ignorespaces The number of hits, and the average reconstructed hit charge, as a function of distance of the collection point from the nearest APA gap.}}{166}{figure.caption.129}
\contentsline {figure}{\numberline {7.21}{\ignorespaces Event display of an APA gap-crossing track, focussed on the gap region.}}{166}{figure.caption.130}
\contentsline {figure}{\numberline {7.22}{\ignorespaces Method to align track segments on either side of the APAs involving minimising residuals from linear least square fit.}}{169}{figure.caption.131}
\contentsline {figure}{\numberline {7.23}{\ignorespaces Method to align track segments on either side of the APAs involving minimising the distance between the projected intersection of each with the centre of the APAs.}}{169}{figure.caption.131}
\contentsline {figure}{\numberline {7.24}{\ignorespaces Difference between the T0 calculated from TPC data and the T0 provided by the counters representing the trigger time of the through-going muon, for simulation and data.}}{170}{figure.caption.132}
\contentsline {figure}{\numberline {7.25}{\ignorespaces Correcting for T0 using $T_0^{\mathrm {counter}}$ and $T_0^{\mathrm {TPC}}$.}}{171}{figure.caption.133}
\contentsline {figure}{\numberline {7.26}{\ignorespaces Demonstration of the effect observed in the 35\nobreakspace {}ton data concerning tracks crossing the APAs.}}{171}{figure.caption.134}
\contentsline {figure}{\numberline {7.27}{\ignorespaces Attempting to correct the track segment misalignment by assuming a misunderstanding of the spacing between the collection planes.}}{172}{figure.caption.136}
\contentsline {figure}{\numberline {7.28}{\ignorespaces Attempting to correct the track segment misalignment by assuming a misunderstanding of the positioning of the collection wires inside the detector.}}{173}{figure.caption.137}
\contentsline {figure}{\numberline {7.29}{\ignorespaces Attempting to correct the track segment misalignment by assuming an incorrect drift velocity.}}{173}{figure.caption.139}
\contentsline {figure}{\numberline {7.30}{\ignorespaces Measuring the drift velocity of the ionisation electrons by taking tracks passing through opposite counter pairs and comparing the corresponding drift distance to the drift time.}}{174}{figure.caption.140}
\contentsline {figure}{\numberline {7.31}{\ignorespaces The T0-corrected drift time for hits on APA-crossing tracks.}}{175}{figure.caption.142}
\contentsline {figure}{\numberline {7.32}{\ignorespaces Difference between the interaction time measured by the TPC data and that provided by photon detector information.}}{175}{figure.caption.143}
\contentsline {figure}{\numberline {7.33}{\ignorespaces The difference between the timestamps recorded by the PTB and the RCEs upon receiving a trigger.}}{176}{figure.caption.144}
\contentsline {figure}{\numberline {7.34}{\ignorespaces The distribution of the drift times of all hits on APA-crossing tracks after correcting for the APA offsets along the direction parallel to the drift direction.}}{178}{figure.caption.145}
\contentsline {figure}{\numberline {7.35}{\ignorespaces Accounting for the extra discrepancy in track alignment after fixing for all the measured offsets by assuming a misunderstanding in the collection plane spacing and the $z$-positions of the collection wires.}}{179}{figure.caption.146}
\contentsline {figure}{\numberline {7.36}{\ignorespaces The T0-corrected drift time for all hits on an APA-crossing track in simulation.}}{180}{figure.caption.147}
\contentsline {figure}{\numberline {7.37}{\ignorespaces Demonstration of the electron ionisation and hit collection for APA-crossing tracks.}}{181}{figure.caption.148}
\contentsline {figure}{\numberline {7.38}{\ignorespaces Comparison between the T0-corrected hit time distributions on APAs with and without the grounded mesh.}}{182}{figure.caption.149}
\contentsline {figure}{\numberline {7.39}{\ignorespaces Comparison between the distribution of T0-corrected hit times for hits on wires in front of the APA frame and away from the APA frame to validate the functionality of the mesh.}}{183}{figure.caption.150}
\contentsline {figure}{\numberline {7.40}{\ignorespaces Average lifetime-corrected charge per hit for hits on an APA-crossing track separated according to whether or not the hit was collected around the interaction time.}}{183}{figure.caption.151}
\contentsline {figure}{\numberline {7.41}{\ignorespaces Event display of an APA-crossing track with the charge deposited as it passes through the APAs evident.}}{185}{figure.caption.152}
\contentsline {figure}{\numberline {7.42}{\ignorespaces Using APA-crossing tracks to confirm the drift velocity is consistent between the two drift regions.}}{186}{figure.caption.153}
\contentsline {figure}{\numberline {7.43}{\ignorespaces Comparison of noise levels between the two drift regions using APA-crossing tracks.}}{186}{figure.caption.154}
\contentsline {figure}{\numberline {7.44}{\ignorespaces The bias in the hit selection due to a high noise level in the 35\nobreakspace {}ton data.}}{188}{figure.caption.155}
\contentsline {figure}{\numberline {7.45}{\ignorespaces The dE/dx distribution for mips passing through the 35\nobreakspace {}ton TPC.}}{189}{figure.caption.156}
\contentsline {figure}{\numberline {7.46}{\ignorespaces Relationship between deposited charge and energy for 35\nobreakspace {}ton data, calculated using through-going mips.}}{190}{figure.caption.157}
\contentsline {figure}{\numberline {7.47}{\ignorespaces Result of applying the shower reconstruction on a shower observed in the 35\nobreakspace {}ton data.}}{191}{figure.caption.158}
\contentsline {figure}{\numberline {7.48}{\ignorespaces A candidate $\pi ^0$ event observed in the online event display during the run.\relax }}{192}{figure.caption.159}
\addvspace {10\p@ }
\addvspace {10\p@ }
\addvspace {10\p@ }
\addvspace {10\p@ }
