\addvspace {10\p@ }
\addvspace {10\p@ }
\contentsline {figure}{\numberline {2.1}{\ignorespaces Energy spectrum of the electron produced in beta decay.}}{4}{figure.caption.7}
\contentsline {figure}{\numberline {2.2}{\ignorespaces Measurements of the hadron production cross-section around the Z resonance.}}{7}{figure.caption.8}
\contentsline {figure}{\numberline {2.3}{\ignorespaces Solar neutrino energy spectra as predicted by the Standard Solar Model \cite {Bahcall2005}. The solid lines represent neutrinos produced during the p-p chain and dashed line represent neutrinos from the CNO cycle. Each spectrum illustrates a particular reaction during the process of a given chain.\relax }}{8}{figure.caption.9}
\contentsline {figure}{\numberline {2.4}{\ignorespaces The double ratio \textit {R} of muon to electron neutrino events showing data divided by expectation \cite {Mann1999}. Various underground atmospheric neutrino detectors are shown.\relax }}{10}{figure.caption.10}
\contentsline {figure}{\numberline {2.5}{\ignorespaces Zenith angle distributions of $\mu $-like and $e$-like events for sub-GeV and multi-GeV data sets. Upward-going particles have $\qopname \relax o{cos}{\Theta } < 0$ and downward-going particles have $\qopname \relax o{cos}{\Theta } > 0$. The hatched region shows the Monte Carlo expectation for no oscillations and the bold line is the best-fit expectation for $\nu _{\mu }\rightarrow \nu _{\tau }$ oscillations. Taken from \cite {SuperKamiokande1998}.\relax }}{12}{figure.caption.11}
\contentsline {figure}{\numberline {2.6}{\ignorespaces The ratio of the number of data events to Monte Carlo events in the absence of oscillations as a function of reconstructed $L/E_{\nu }$. The dashed lines show the expected shape for $\nu _{\mu }\rightarrow \nu _{\tau }$ oscillations. Taken from \cite {SuperKamiokande1998}.\relax }}{12}{figure.caption.12}
\contentsline {figure}{\numberline {2.7}{\ignorespaces Comparison of the predictions of the neutrino fluxes from the Standard Solar Model with measured rates from a variety of solar neutrino experiments. The results of SNO (D$_2$O target, right two comparisons) show that the expected flux is observed, but not necessarily as electron neutrinos. This shows conclusively the oscillatory nature of neutrinos.\relax }}{14}{figure.caption.13}
\contentsline {figure}{\numberline {2.8}{\ignorespaces General scattering mechanics which occur as neutrinos pass through matter. Neutral current scattering (Figure\nobreakspace {}\ref {fig:MatterEffectsNC}) occurs for all neutrino flavour combinations whereas charged current scattering (Figure\nobreakspace {}\ref {fig:MatterEffectsCC}) only occurs when the incoming leptons have the same flavour.\relax }}{18}{figure.caption.14}
\contentsline {figure}{\numberline {2.9}{\ignorespaces Global 3-neutrino oscillation analysis taken from \cite {NuFit2014,NuFit2017}. Each panel shows the two-dimensional projection of the allowed six-dimensional region after marginalisation with respect to the undisplayed parameters. The different contours correspond to 1$\sigma $, 90\%, 2$\sigma $, 99\%, 3$\sigma $ CL (2 dof).\relax }}{21}{figure.caption.15}
\contentsline {figure}{\numberline {2.10}{\ignorespaces Demonstration of the current uncertainties in the neutrino mass.}}{23}{figure.caption.17}
\addvspace {10\p@ }
\contentsline {figure}{\numberline {3.1}{\ignorespaces Cartoon showing the configuration of the Deep Underground Neutrino Experiment.}}{26}{figure.caption.18}
\contentsline {figure}{\numberline {3.2}{\ignorespaces Original TPC design, Nygren (1974)}}{27}{figure.caption.19}
\contentsline {figure}{\numberline {3.3}{\ignorespaces First LArTPC detector, Rubbia (1977)}}{28}{figure.caption.21}
\contentsline {figure}{\numberline {3.4}{\ignorespaces Effect of electric field on luminosity of ionisation electrons and scintillation light in a LArTPC.}}{30}{figure.caption.22}
\contentsline {figure}{\numberline {3.5}{\ignorespaces Schematic demonstrating the basic operational principles of a LArTPC.}}{31}{figure.caption.23}
\contentsline {figure}{\numberline {3.6}{\ignorespaces Demonstration of how having access to multiple oscillation maxima facilitates measurements of both the neutrino mass hierarchy and leptonic CP violation using the same experiment.}}{33}{figure.caption.24}
\contentsline {figure}{\numberline {3.7}{\ignorespaces Longitudinal section of the LBNF beamline facility at Fermilab \cite {DUNECDR3}.\relax }}{35}{figure.caption.25}
\contentsline {figure}{\numberline {3.8}{\ignorespaces The fluxes of the different neutrino flavour components of the DUNE beam in neutrino and antineutrino running mode.}}{36}{figure.caption.26}
\contentsline {figure}{\numberline {3.9}{\ignorespaces The layout of the four cryostats underground at SURF comprising the DUNE far detector.}}{37}{figure.caption.27}
\contentsline {figure}{\numberline {3.10}{\ignorespaces The basic design of a single-phase DUNE far detector module.}}{38}{figure.caption.28}
\contentsline {figure}{\numberline {3.11}{\ignorespaces Design of a DUNE far detector Anode Plane Assembly (APA).}}{39}{figure.caption.29}
\contentsline {figure}{\numberline {3.12}{\ignorespaces The design of the photon detectors for the DUNE far detector.}}{41}{figure.caption.30}
\contentsline {figure}{\numberline {3.13}{\ignorespaces The DUNE dual-phase detector (partially open).}}{42}{figure.caption.31}
\contentsline {figure}{\numberline {3.14}{\ignorespaces The extraction, amplification and readout of the ionisation electrons through the gaseous argon phase in the DUNE dual-phase LArTPC design.}}{42}{figure.caption.32}
\contentsline {figure}{\numberline {3.15}{\ignorespaces Schematic of the DUNE near neutrino detector fine-grained tracker design.}}{44}{figure.caption.33}
\contentsline {figure}{\numberline {3.16}{\ignorespaces The appearance probability at a baseline of 1300\nobreakspace {}km, as a function of neutrino energy, for $\delta _{CP}=-\pi /2$ (blue), 0 (red) and $\pi /2$ (green) for neutrinos (left) and antineutrinos (right), for normal hierarchy. The black lines indicates the oscillation probability if $\theta _{13}$ were equal to zero. Taken from \cite {DUNECDR2}.\relax }}{47}{figure.caption.35}
\contentsline {figure}{\numberline {3.17}{\ignorespaces Sensitivity of the DUNE experiment to the neutrino mass hierarchy.}}{48}{figure.caption.36}
\contentsline {figure}{\numberline {3.18}{\ignorespaces Sensitivity of the DUNE experiment to leptonic CP violation.}}{50}{figure.caption.37}
\contentsline {figure}{\numberline {3.19}{\ignorespaces The sensitivity of DUNE to the octant and value of $\theta _{23}$.}}{51}{figure.caption.38}
\contentsline {figure}{\numberline {3.20}{\ignorespaces The sensitivity of DUNE to the oscillation parameters describing $\nu _e$ and $\bar {\nu }_e$ appearance.}}{52}{figure.caption.39}
\contentsline {figure}{\numberline {3.21}{\ignorespaces The 35\nobreakspace {}ton cryostat and detector designed to prototype the DUNE far detector design.}}{54}{figure.caption.40}
\contentsline {figure}{\numberline {3.22}{\ignorespaces Schematic showing the layout of the ProtoDUNEs at the CERN neutrino platform.}}{55}{figure.caption.41}
\addvspace {10\p@ }
\contentsline {figure}{\numberline {4.1}{\ignorespaces LAPD tank and purification system}}{59}{figure.caption.42}
\contentsline {figure}{\numberline {4.2}{\ignorespaces Contaminant gradient in the LAPD tank}}{60}{figure.caption.43}
\contentsline {figure}{\numberline {4.3}{\ignorespaces Design of LAPD and 35\nobreakspace {}ton style purity monitors}}{61}{figure.caption.44}
\contentsline {figure}{\numberline {4.5}{\ignorespaces The 35\nobreakspace {}ton cryostat}}{63}{figure.caption.46}
\addvspace {10\p@ }
\addvspace {10\p@ }
\contentsline {figure}{\numberline {6.1}{\ignorespaces The \textit {lbne-artdaq} framework}}{70}{figure.caption.48}
\contentsline {figure}{\numberline {6.2}{\ignorespaces Software framework built for 35\nobreakspace {}ton Online Monitoring}}{72}{figure.caption.49}
\contentsline {figure}{\numberline {6.3}{\ignorespaces Selection of Data Quality Monitoring figures}}{76}{figure.caption.50}
\contentsline {figure}{\numberline {6.4}{\ignorespaces 35\nobreakspace {}ton data format}}{78}{figure.caption.51}
\contentsline {figure}{\numberline {6.5}{\ignorespaces Demonstration of how TPC data from a triggered event in a LArTPC is saved when employing a DAQ with continuous readout}}{79}{figure.caption.52}
\contentsline {figure}{\numberline {6.6}{\ignorespaces Example online event display made by the Online Monitoring framework}}{81}{figure.caption.53}
\contentsline {figure}{\numberline {6.7}{\ignorespaces Schematic showing the interface between the online monitoring system and the web}}{82}{figure.caption.54}
\contentsline {figure}{\numberline {6.8}{\ignorespaces Web page for online monitoring and event displays}}{83}{figure.caption.55}
\addvspace {10\p@ }
\contentsline {figure}{\numberline {7.1}{\ignorespaces `Good' and `bad' 35\nobreakspace {}ton runs}}{86}{figure.caption.56}
\contentsline {figure}{\numberline {7.2}{\ignorespaces Correcting for stuck codes in the 35\nobreakspace {}ton data}}{87}{figure.caption.57}
\contentsline {figure}{\numberline {7.3}{\ignorespaces Raw data stuck bit mitigation}}{88}{figure.caption.58}
\contentsline {figure}{\numberline {7.4}{\ignorespaces Coherent noise removal in 35\nobreakspace {}ton data}}{88}{figure.caption.59}
\contentsline {figure}{\numberline {7.5}{\ignorespaces Selecting tracks for 35\nobreakspace {}ton data analysis}}{90}{figure.caption.60}
\contentsline {figure}{\numberline {7.6}{\ignorespaces Event display showing tracks passing across APA gaps and also through the APAs.}}{92}{figure.caption.61}
\contentsline {figure}{\numberline {7.7}{\ignorespaces Schematic showing an example APA gap-crossing track as viewed looking down from the top of the detector. The vertical direction represents the drift direction ($x$); the horizontal direction represents the $z$-direction. In general, these tracks make an angle with respect to the face of the APAs, as shown in the figure. As the gap in between the APAs is uninstrumented, no charge is desposited in this region.\relax }}{93}{figure.caption.62}
\contentsline {figure}{\numberline {7.8}{\ignorespaces Schematic showing an example track crossing two drift regions offset by an unknown quantity $\Delta z$. The effect of this is evident from the track desposits (Figure\nobreakspace {}\ref {fig:APAGapZOffsetUncorrected}) and can be corrected by ensuring the segments are aligned between the TPCs (Figure\nobreakspace {}\ref {fig:APAGapZOffsetCorrected}).\relax }}{94}{figure.caption.63}
\contentsline {figure}{\numberline {7.9}{\ignorespaces Illustration of the eight gaps between the four APA frames.\relax }}{94}{figure.caption.64}
\contentsline {figure}{\numberline {7.10}{\ignorespaces The $z$-offset for the TPC5/TPC7 gap measured in the 35\nobreakspace {}ton data. A very noticable double-peak structure is evident in Figure\nobreakspace {}\ref {fig:TPC5TPC7Gap}; this bias appears to be related to the sign of the angle the particle track makes to the APA planes.\relax }}{96}{figure.caption.65}
\contentsline {figure}{\numberline {7.11}{\ignorespaces Demonstration of how an $x$-offset in the positions of the APAs can explain the degeneracy evident in the $z$-offset measured using the 35\nobreakspace {}ton data (Figure\nobreakspace {}\ref {fig:TPC5TPC7XOffsetZOffset}). In the left-hand plots, Figures\nobreakspace {}\ref {fig:APAGapXOffsetPos} and\nobreakspace {}\ref {fig:APAGapXOffsetPosFix}, the through-going particle makes a positive angle to the face of the APAs and in the right-hand plots, Figures\nobreakspace {}\ref {fig:APAGapXOffsetNeg} and\nobreakspace {}\ref {fig:APAGapXOffsetNegFix}, the particle is travelling with a negative gradient. In both cases, the offset of the APAs in the $x$-direction is the same. It is clear from Figures\nobreakspace {}\ref {fig:APAGapXOffsetPosFix} and\nobreakspace {}\ref {fig:APAGapXOffsetNegFix} how the sign of the measured $\Delta z$ is dependent on the angle of the track.\relax }}{97}{figure.caption.66}
\contentsline {figure}{\numberline {7.12}{\ignorespaces Studies of the effects of offsets in the positions of the APAs in simulation. Articficial $z$- and $x$- offsets are introduced and their impact observed in the measurements of $\Delta z$. Figure\nobreakspace {}\ref {fig:APAGapMCZOffset} shows the effect of an offset in the $z$-direction; as expected, there is a single peak measuring the inputed value. Figures\nobreakspace {}\ref {fig:APAGapMCXOffsetZOffset} and\nobreakspace {}\ref {fig:APAGapMCXOffsetZOffsetAngle} show the consequence of offsets in both the $x$- and $z$-directions. This appears to show exactly what is seen in the 35\nobreakspace {}ton data (Figure\nobreakspace {}\ref {fig:TPC5TPC7XOffsetZOffset}).\relax }}{98}{figure.caption.67}
\contentsline {figure}{\numberline {7.13}{\ignorespaces {\color {red} Same as previous page -- which is better? I prefer the layout of the previous page but I like this one because you can see the 2cm offset in line with each other down the page!} Studies of the effects of offsets in the positions of the APAs in simulation. Articficial $z$- and $x$- offsets are introduced and their impact observed in the measurements of $\Delta z$. Figure\nobreakspace {}\ref {fig:APAGapMCZOffset} shows the effect of an offset in the $z$-direction; as expected, there is a single peak measuring the inputed value. Figures\nobreakspace {}\ref {fig:APAGapMCXOffsetZOffset} and\nobreakspace {}\ref {fig:APAGapMCXOffsetZOffsetAngle} show the consequence of offsets in both the $x$- and $z$-directions. This appears to show exactly what is seen in the 35\nobreakspace {}ton data (Figure\nobreakspace {}\ref {fig:TPC5TPC7XOffsetZOffset}).\relax }}{99}{figure.caption.68}
\contentsline {figure}{\numberline {7.14}{\ignorespaces Demonstration of the effects of offsets in both the $x$- and $z$-directions in the determination of $\Delta z$ between TPC5 and TPC7. With an $x$-offset present, it is impossible for the true value of $\Delta z$ to be measured -- this is evident from Figure\nobreakspace {}\ref {fig:APAGapMC}. It is clear from these geometrical considerations how the measured offset $\Delta z_m$ will populate distributions either side of the true value; the true value $\Delta z$ is given by the minimum between the two distributions.\relax }}{100}{figure.caption.69}
\contentsline {figure}{\numberline {7.15}{\ignorespaces Extraction of the true value of $\Delta z$ from the full distribution of measured $z$-offsets. A measured value of $0.117\pm 0.007$\nobreakspace {}cm is found.\relax }}{101}{figure.caption.70}
\contentsline {figure}{\numberline {7.16}{\ignorespaces Measurement of the $x$-offset between TPC5 and TPC7 after applying the $z$-gap corrected determined using the method described in the text and Figure\nobreakspace {}\ref {fig:TPC5TPC7GapFit}. A measurement of $-0.286\pm 0.002$\nobreakspace {}cm is determined.\relax }}{101}{figure.caption.71}
\contentsline {figure}{\numberline {7.17}{\ignorespaces Measurement of the $z$-offset between TPC5 and TPC7 after applying the $x$-offset determined from Figure\nobreakspace {}\ref {fig:TPC5TPC7XOff}. As initially anticipated, there is a single peak distributed around the true value of the offset. This validates the method used and confirms the initial presence of an $x$-offset between the neighbouring APAs. The final measurement of $\Delta z$ is $0.103\pm 0.004$\nobreakspace {}cm which agrees reasonably with the value measured previously ($0.117\pm 0.007$\nobreakspace {}cm from Figure\nobreakspace {}\ref {fig:TPC5TPC7GapFit}).\relax }}{102}{figure.caption.72}
\contentsline {figure}{\numberline {7.18}{\ignorespaces Number of reconstructed hits at different distances from nearest APA gap.}}{106}{figure.caption.74}
\contentsline {figure}{\numberline {7.19}{\ignorespaces The average charge of hits as a function of distance to nearest APA gap.}}{106}{figure.caption.74}
\contentsline {figure}{\numberline {7.20}{\ignorespaces Event display of an APA gap-crossing track, focussed on the gap region.}}{107}{figure.caption.75}
\contentsline {figure}{\numberline {7.21}{\ignorespaces Method to align track segments on either side of the APAs involving minimising residuals from linear least square fit.}}{109}{figure.caption.76}
\contentsline {figure}{\numberline {7.22}{\ignorespaces Method to align track segments on either side of the APAs involving minimising the distance between the projected intersection of each with the centre of the APAs.}}{109}{figure.caption.76}
\contentsline {figure}{\numberline {7.23}{\ignorespaces Difference between the T0 calculated from TPC data and the T0 provided by the counters representing the trigger time of the through-going muon, for simulation and data.}}{110}{figure.caption.77}
\contentsline {figure}{\numberline {7.24}{\ignorespaces Correcting for T0 using $T_0^{\mathrm {counter}}$ and $T_0^{\mathrm {TPC}}$.}}{111}{figure.caption.78}
\contentsline {figure}{\numberline {7.25}{\ignorespaces Demonstration of the effect observed in the 35\nobreakspace {}ton data concerning tracks crossing the APAs.}}{111}{figure.caption.79}
\contentsline {figure}{\numberline {7.26}{\ignorespaces Attemping to correct the track segment misalignment by assuming a misunderstanding of the spacing between the collection planes.}}{112}{figure.caption.81}
\contentsline {figure}{\numberline {7.27}{\ignorespaces Attempting to correct the track segment misalignment by assuming a misunderstanding of the positioning of the collection wires inside the detector.}}{113}{figure.caption.82}
\contentsline {figure}{\numberline {7.28}{\ignorespaces Attempting to correct the track segment misalignment by assuming an incorrect drift velocity.}}{113}{figure.caption.84}
\contentsline {figure}{\numberline {7.29}{\ignorespaces Measuring the drift velocity of the ionisation electrons by taking tracks passing through opposite counter pairs and comparing the corresponding drift distance to the drift time.}}{114}{figure.caption.85}
\contentsline {figure}{\numberline {7.30}{\ignorespaces The T0-corrected drift time for hits on APA-crossing tracks.}}{115}{figure.caption.87}
\contentsline {figure}{\numberline {7.31}{\ignorespaces Difference between the interaction time measured by the TPC data and that provided by photon detector information.}}{115}{figure.caption.88}
\contentsline {figure}{\numberline {7.32}{\ignorespaces The difference between the timestamps recorded by the PTB and the RCEs upon recieving a trigger.}}{116}{figure.caption.89}
\contentsline {figure}{\numberline {7.33}{\ignorespaces The distribution of the drift times of all hits on APA-crossing tracks after correcting for the APA offsets along the direction parallel to the drift direction.}}{118}{figure.caption.90}
\contentsline {figure}{\numberline {7.34}{\ignorespaces Accounting for the extra disprecency in track alignment after fixing for all the measured offsets by assuming a misunderstanding in the collection plane spacing and the $z$-positions of the collection wires.}}{119}{figure.caption.91}
\contentsline {figure}{\numberline {7.35}{\ignorespaces The T0-corrected drift time for all hits on an APA-crossing track in simulation.}}{120}{figure.caption.92}
\contentsline {figure}{\numberline {7.36}{\ignorespaces Demonstration of the electron ionisation and hit collection for APA-crossing tracks.}}{121}{figure.caption.93}
\contentsline {figure}{\numberline {7.37}{\ignorespaces Comparison between the T0-corrected hit time distributions on APAs with and without the grounded mesh.}}{122}{figure.caption.94}
\contentsline {figure}{\numberline {7.38}{\ignorespaces Comparison between the distribution of T0-corrected hit times for hits on wires in front of the APA frame and away from the APA frame to validate the functionality of the mesh.}}{123}{figure.caption.95}
\contentsline {figure}{\numberline {7.39}{\ignorespaces Average lifetime-corrected charge per hit for hits on an APA-crossing track separated according to whether or not the hit was collected around the interaction time.}}{123}{figure.caption.96}
\contentsline {figure}{\numberline {7.40}{\ignorespaces Event display of an APA-crossing track with the charge deposited as it passes through the APAs evident.}}{125}{figure.caption.97}
\contentsline {figure}{\numberline {7.41}{\ignorespaces Using APA-crossing tracks to confirm the drift velocity is consistent between the two drift regions.}}{126}{figure.caption.98}
\contentsline {figure}{\numberline {7.42}{\ignorespaces Comparison of noise levels between the two drift regions using APA-crossing tracks.}}{126}{figure.caption.99}
\contentsline {figure}{\numberline {7.43}{\ignorespaces The bias in the hit selection due to a high noise level in the 35\nobreakspace {}ton data.}}{128}{figure.caption.100}
\contentsline {figure}{\numberline {7.44}{\ignorespaces The dE/dx distribution for MIPs passing through the 35\nobreakspace {}ton TPC.}}{129}{figure.caption.101}
\contentsline {figure}{\numberline {7.45}{\ignorespaces Relationship between deposited charge and energy for 35\nobreakspace {}ton data, calculated using through-going MIPs.}}{130}{figure.caption.102}
\contentsline {figure}{\numberline {7.46}{\ignorespaces Result of applying the shower reconstruction on a shower observed in the 35\nobreakspace {}ton data.}}{131}{figure.caption.103}
\contentsline {figure}{\numberline {7.47}{\ignorespaces A candidate $\pi ^0$ event observed in the online event display during the run.\relax }}{132}{figure.caption.104}
\addvspace {10\p@ }
\addvspace {10\p@ }
\addvspace {10\p@ }
\addvspace {10\p@ }
